### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by ZongyueZhao** [seowok/TreeGAN#2]
To whom it may concern,

Would you please provide a introduction/code on data preparation? Currently the scripts in ./data are not compatible with the shapenet dataset you linked.

#1 points out a missing text file, which seems to be the mapping between the numbers to class names. However, the following data/paths cannot be found in the linked shapenet dataset.

`SAVE_DIR = 'C:/dataset/Spatial/'
#SAVE_DIR = '/home/cvml/spatial/dataset/Spatial/'
IMAGE_DIR = 'D:/dataset/ShapeNetRendering/'
POINT_DIR = 'D:/dataset/ShapeNetPointcloud/'
OBJ_DIR = 'D:/dataset/ShapeNetCore.v2/'`

Thank you for your time and effort!

**Comment by seowok** [comment]
I updated your commented error. 
Now, you can find under './data' folder. 
Thank you for your comment.
