### ISSUE TITLE
Data  Download and Preparation

### ISSUE THREAD

**Issue by Timaces** [seowok/TreeGAN#3]
To whom it may concern,

Hi，after you updated the code ,I found the data Download is not provided ,So I Download it in here : https://www.dropbox.com/s/vmsdrae6x5xws1v/shape_net_core_uniform_samples_2048.zip?dl=0.

when  I run the train.py ,the questiuon is : FileNotFoundError: [Errno 2] No such file or directory: '/home/l/Downloads/TreeGAN-master/data/03790512/points'. IT may have something to do with the code：            
            dir_point = os.path.join(self.root, self.cat[item], 'points')
            dir_seg = os.path.join(self.root, self.cat[item], 'points_label')
            dir_sampling = os.path.join(self.root, self.cat[item], 'sampling')
So ，After downloading the data, what do I need to do before I start running the program?

You can write a tutorial like we can reproduce your task. Thank you very much.

Thank you for your time and effort!

**Comment by munnam77** [comment]
You can check and change the path of the dataset in arguments.py
