### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by samiarshad** [seowok/TreeGAN#4]
Hi,

I am trying to recreate your results. Would you please share the dataset you've used to train the model.

Thanks

**Comment by seowok** [comment]
https://shapenet.cs.stanford.edu/ericyi/shapenetcore_partanno_segmentation_benchmark_v0.zip

This link are attached in our README.md as hyperlink text.

This dataset is used for FPD and our model also use it.

Thanks.

**Comment by samiarshad** [comment]
Thanks for the information.
