### ISSUE TITLE
Auto encoding and shape interpolation

### ISSUE THREAD

**Issue by NolenChen** [seowok/TreeGAN#6]
Thank you for sharing the code.

I've read the paper. I want to know the way to do the point cloud auto-encoding as show in figure 7 in the paper. Since the generator in the GAN is used to generate a shape from a random latent code.  There should be an point cloud encoder in order to achieve the point cloud auto-encoding(Fig 7) as well as interpolation between two given point clouds. Could you tell me more detail about what encoder is used as well as the way to train, since I cannot find the detailed description about this.

Moreover, could you tell me where I can find the supplementary material.

Thanks again for your excellent work.

**Comment by seowok** [comment]
Actually this work is not auto encoder based model, but WGAN-GP. 

As you know, GAN based model uses random variable sampled from specific distribution(i.e. Gaussian Distribution).

So our model also use random variables sampled from N(0,I) as like latent vector in auto encoder based model [Normal dist.]

Interpolation also can work between two random variables z ~ N(0,I).

Thank you for your attention to our work.
